server:
  port: 8080
eureka: 
  client: 
    fetch-registry: true
    register-with-eureka: true
    service-url:
      default-zone: http://localhost:8761/eureka
  instance:
    hostname: localhost

spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: msc-persona
          uri: lb://msc-persona
          predicates:
            - Path=/persona/**
        - id: msc-personal
          uri: lb://msc-personal
          predicates:
            - Path=/personal/**
        - id: swagger-personal
          uri: lb://msc-personal
          predicates:
            - Path=/swagger/personal/**
          filters:
            - RewritePath=/swagger/personal/(?<segment>.*), /${segment}
              # Opcional: Agrega cabecera X-Frame-Options
            - AddResponseHeader=X-Frame-Options, SAMEORIGIN
            - StripPrefix=2
        - id: swagger-persona
          uri: lb://msc-persona
          predicates:
            - Path=/swagger/persona/**
          filters:
            - RewritePath=/swagger/persona/(?<segment>.*), /${segment}
              # Opcional: Agrega cabecera X-Frame-Options
            - AddResponseHeader=X-Frame-Options, SAMEORIGIN
            - StripPrefix=2        

      