server:
  port: 8080
eureka: 
  client: 
    fetch-registry: true
    register-with-eureka: true
    service-url:
      default-zone: http://localhost:8761/eureka
  instance:
    hostname: localhost

spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: msc-persona
          uri: lb://msc-persona
          predicates:
            - Path=/persona/**
        - id: msc-personal
          uri: lb://msc-personal
          predicates:
            - Path=/personal/**
        - id: swagger-personal
          uri: lb://msc-personal
          predicates:
            - Path=/swagger-personal/** # Cambiar a /swagger-personal/**
          filters:
            - RewritePath=/swagger-ui/(?<segment>.*), /${segment}
            - AddResponseHeader=X-Frame-Options, SAMEORIGIN
        - id: swagger-persona
          uri: lb://msc-persona
          predicates:
            - Path=/swagger-persona/** # Cambiar a /swagger-persona/**
          filters:
            - RewritePath=/swagger-ui/(?<segment>.*), /${segment}
            - AddResponseHeader=X-Frame-Options, SAMEORIGIN

      