server:
  port: 8080
eureka: 
  client: 
    fetch-registry: true
    register-with-eureka: true
    service-url:
      default-zone: http://localhost:8761/eureka
  instance:
    hostname: localhost

spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: msc-persona
          uri: lb://msc-persona
          predicates:
            - Path=/persona/**
        - id: msc-personal
          uri: lb://msc-personal
          predicates:
            - Path=/personal/**
        

      