spring:
  cloud:
    discovery:
      client:
        registration:
          msc-persona:
            port: ${PORT:${SERVER_PORT:0}}
eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      default-zone: http://localhost:8761/eureka
    instance:
      instanceId: ${spring.application.name}:${spring.application.instance_id:${random.value}}
      metadata:
        instanceId: ${spring.application.instance_id:${random.value}}
      leaseRenewalIntervalInSeconds: 10 # ajusta este valor según tus necesidades
      leaseExpirationDurationInSeconds: 30 # ajusta este valor según tus necesidades
      nonSecurePort: ${server.port:${SERVER_PORT:0}}