server:
  port: 8001

spring:
  cloud:
    config:
      server:
        git:
          default-label: main
          uri: https://github.com/Steven77dev/syst-restaurante
          search-paths: config-data
  application:
    name: config-server