server:
  port: 8001

spring:
  cloud:
    config:
      server:
        git:
          default-label: master
          uri: https://github.com/Steven77dev/backend-msc-sgr
          search-paths: config-data
  application:
    name: config-server