server:
  port: 8001

spring:
  cloud:
    config:
      server:
        git:
          default-label: master
          uri: https://github.com/Steven77dev/backend-msc-sgr.git
          search-paths: config-data
          username: steven77dev
          password: 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
  application:
    name: config-server